name: task_tracker
description: "Task Tracker Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.4
  firebase_core: ^2.28.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true