// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3unMtp2wLFbqlDLpv1bsAhUvMwRxJQpM',
    appId: '1:51697225038:web:a1e0772120cda98501a21f',
    messagingSenderId: '51697225038',
    projectId: 'task-tracker-new-41c17',
    authDomain: 'task-tracker-new-41c17.firebaseapp.com',
    storageBucket: 'task-tracker-new-41c17.firebasestorage.app',
    measurementId: 'G-REBWWE4NVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzhK1g6ERdfzSLLbn07ESmP8hI9MemjPA',
    appId: '1:51697225038:android:41df400a8277eb8f01a21f',
    messagingSenderId: '51697225038',
    projectId: 'task-tracker-new-41c17',
    storageBucket: 'task-tracker-new-41c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74SISZMEbuuzAXQu3deUH7Wq4kzNUUpY',
    appId: '1:51697225038:ios:1f0f945a3863ec2501a21f',
    messagingSenderId: '51697225038',
    projectId: 'task-tracker-new-41c17',
    storageBucket: 'task-tracker-new-41c17.firebasestorage.app',
    iosBundleId: 'com.example.taskTrackerNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC74SISZMEbuuzAXQu3deUH7Wq4kzNUUpY',
    appId: '1:51697225038:ios:1f0f945a3863ec2501a21f',
    messagingSenderId: '51697225038',
    projectId: 'task-tracker-new-41c17',
    storageBucket: 'task-tracker-new-41c17.firebasestorage.app',
    iosBundleId: 'com.example.taskTrackerNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3unMtp2wLFbqlDLpv1bsAhUvMwRxJQpM',
    appId: '1:51697225038:web:3a96bf67794dc4ff01a21f',
    messagingSenderId: '51697225038',
    projectId: 'task-tracker-new-41c17',
    authDomain: 'task-tracker-new-41c17.firebaseapp.com',
    storageBucket: 'task-tracker-new-41c17.firebasestorage.app',
    measurementId: 'G-VXSHEW99ED',
  );
}
